name: Security Test Matrix
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  security:
    uses: 0ponn/devsec-baseline/.github/workflows/security.yaml@main
    permissions:
      contents: read
      actions: read
      security-events: write
